//Store client config values here

import config from './../../server/config';

const defaults = {
  debug: true, //Includes stats and helpers
  kinecttransport: {
    ports: {
      outgoing: config.kinectTransport.ports.outgoing,
    },
  },
  rooms: [
    {
      id: 0, name: 'The Void Calm',
      type: 'empty',
      enabled: true, colored: false,
      colorURL: '', bwURL: '',
      position: new THREE.Vector3(0, 0, 0),
      rotation: new THREE.Euler(),
      scale: 0,
      objects: [
        {
          type: 'cube', active: true,
          scale: 0.5,
          position: new THREE.Vector3(-1, 1, -2),
          rotation: new THREE.Euler(),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
        {
          type: 'cube', active: false,
          scale: 0.5,
          position: new THREE.Vector3(0, 1, -2),
          rotation: new THREE.Euler(),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
        {
          type: 'cube', active: false,
          scale: 0.5,
          position: new THREE.Vector3(1, 1, -2),
          rotation: new THREE.Euler(),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
      ],
      musicURL: '',
    },
    {
      id: 1, name: 'The Armoury',
      type: 'gltf',
      enabled: false, colored: false,
      colorURL: 'models/gltf/the_armoury/scene.gltf', bwURL: 'models/gltf/the_armoury/textures/model_Material_u1_v1_baseColor_bw.jpeg',
      position: new THREE.Vector3(0.2, -0.35, -2.4),
      rotation: new THREE.Euler(0, 0.8, 0),
      scale: 0.28,
      objects: [
        {
          type: 'cube', active: false,
          scale: 0.5,
          position: new THREE.Vector3(-3.5, 2, -0.5),
          rotation: new THREE.Euler(),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
        {
          type: 'sword', active: false,
          scale: 0.002,
          colorURL: 'models/gltf/kama_dagger/scene.gltf',
          position: new THREE.Vector3(2.55, 1.5, 0.96),
          rotation: new THREE.Euler(0, Math.PI/2, Math.PI/2),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
        {
          type: 'gun', active: false,
          scale: 0.01,
          colorURL: 'models/gltf/flintlock_pistol/scene.gltf',
          position: new THREE.Vector3(0.8, 1, -2.35),
          rotation: new THREE.Euler(Math.PI/2, 0, -Math.PI/4),
          highlightOffset: new THREE.Vector3(0.8, 1.01, -2.37),
          highlightScale: new THREE.Vector3(0.0105, 0.0105, 0.0105),
        },
        {
          type: 'axe', active: false,
          scale: 0.005,
          colorURL: 'models/gltf/decorative_battle_axe/scene.gltf',
          position: new THREE.Vector3(-2.1, 1.55, -3.45),
          rotation: new THREE.Euler(0, 0, Math.PI/2-0.34),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(1.05, 1.05, 1.05),
        },
      ],
      musicURL: '',
    },
    {
      id: 2, name: 'The Drawing Room',
      type: 'gltf',
      enabled: false, colored: false,
      colorURL: 'models/gltf/the_great_drawing_room/scene.gltf', bwURL: 'models/gltf/the_great_drawing_room/textures/model_Material_u1_v1_baseColor_bw.jpeg',
      position: new THREE.Vector3(-1.6, -0.57, -5),
      rotation: new THREE.Euler(0, 4.5, 0),
      scale: 0.5,
      objects: [
        {
          type: 'cube', active: false,
          scale: 0.5,
          position: new THREE.Vector3(3.75, 2, -1.25),
          rotation: new THREE.Euler(),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
        {
          type: 'violin', active: false,
          scale: 0.01,
          colorURL: 'models/gltf/violin/scene.gltf',
          position: new THREE.Vector3(4, 1, -4.15),
          rotation: new THREE.Euler(0, -1, 0),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
        {
          type: 'mandolin', active: false,
          scale: 0.0015,
          colorURL: 'models/gltf/f-style-mandolin/scene.gltf',
          position: new THREE.Vector3(-4.4, 0.25, -5),
          rotation: new THREE.Euler(-4.6, 3.2, 7.79),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
        {
          type: 'flute', active: false,
          scale: 0.1,
          colorURL: 'models/gltf/maori_nguru_nose_flute/scene.gltf',
          position: new THREE.Vector3(1.75, 0.925, -0.8),
          rotation: new THREE.Euler(0, 0, 1.5),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
      ],
      musicURL: '',
    },
    {
      id: 3, name: 'The Void Storm',
      type: 'empty',
      enabled: false, colored: false,
      colorURL: '', bwURL: '',
      position: new THREE.Vector3(0, -0.345, 0),
      rotation: new THREE.Euler(),
      scale: 0.3,
      objects: [
        {
          type: 'cube', active: true,
          scale: 0.5,
          position: new THREE.Vector3(-1, 1, -2),
          rotation: new THREE.Euler(),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
        {
          type: 'cube', active: true,
          scale: 0.5,
          position: new THREE.Vector3(0, 1, -2),
          rotation: new THREE.Euler(),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
        {
          type: 'cube', active: false,
          scale: 0.5,
          position: new THREE.Vector3(1, 1, -2),
          rotation: new THREE.Euler(),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
      ],
      musicURL: '',
    },
    {
      id: 4, name: 'Mow Cop Castle',
      type: 'gltf',
      enabled: false, colored: true,
      colorURL: 'models/gltf/mow_cop_castle/scene.gltf', bwURL: '',
      position: new THREE.Vector3(-34.99, -27.59, -26.4),
      rotation: new THREE.Euler(0, -1.43, 0),
      scale: 2,
      objects: [
        {
          type: 'kinect', active: false,
          scale: 1,
          position: new THREE.Vector3(0,   1, -2),
          rotation: new THREE.Euler(),
          highlightOffset: new THREE.Vector3(),
          highlightScale: new THREE.Vector3(0.8, 0.8, 0.8),
        },
      ],
      musicURL: '',
    },
  ],
  fonts: [
    {
        name: 'bold',
        json: '/bmFont/lato-bold.json',
        png: '/bmFont/lato-bold.png',
    },
    {
        name: 'regular',
        json: '/bmFont/lato-regular.json',
        png: '/bmFont/lato-regular.png',
    },
  ],
};

module.exports = defaults;
